name: Timetable Reminder

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"
      timezone: "Asia/Kolkata"

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run timetable reminder
        env:
          SENDERS_Email: ${{ secrets.SENDERS_Email }}
          Sender_app_pass: ${{ secrets.Sender_app_pass }}
          Receiver_email: ${{ secrets.Receiver_email }}

        run: python timetable_reminder1.py
