name: Timetable Reminder

on:
  workflow_dispatch:

  schedule:
    - cron: "*/2 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run timetable reminder
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python timetable_reminder1.py
